CREATE DATABASE Manufacturer;

USE Manufacturer


CREATE TABLE Product
(
PROD_ID INT,
PROD_NAME VARCHAR(MAX),
QUANTITY INT
PRIMARY KEY (PROD_ID)
)


---

CREATE TABLE COMPONENT
(
COMP_ID INT PRIMARY KEY,
COMP_NAME VARCHAR(MAX),
[DESCRIPTION] VARCHAR(MAX),
QUANTITY INT 
);


----


CREATE TABLE SUPPLIER
(
SUPP_ID INT,
SUPP_NAME VARCHAR(MAX),
ISACTIVE BIT,
PRIMARY KEY (SUPP_ID)
)


---

CREATE TABLE PROD_COMP
(
PROD_ID INT,
COMP_ID INT,
PRIMARY KEY (PROD_ID, COMP_ID),
FOREIGN KEY (PROD_ID) REFERENCES PRODUCT (PROD_ID),
FOREIGN KEY (COMP_ID) REFERENCES COMPONENT (COMP_ID)
)

---


CREATE TABLE COMP_SUPP
(
COMP_ID INT,
SUPP_ID INT,
ORDER_DATE DATE,
ORDER_QUANTITY INT,
PRIMARY KEY (COMP_ID, SUPP_ID),
FOREIGN KEY (SUPP_ID) REFERENCES SUPPLIER (SUPP_ID),
FOREIGN KEY (COMP_ID) REFERENCES COMPONENT (COMP_ID)
)


© 2021 GitHub, Inc.